# Generated by Django 2.2.7 on 2019-12-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='fio',
        ),
    ]
