# Generated by Django 2.2.7 on 2019-12-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venue', '0004_location_url'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('played', models.BooleanField(default=False, verbose_name='состав подан')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.Event', verbose_name='игра ЧГК')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rating.Team', verbose_name='команда на сайте рейтинга')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'unique_together': {('team', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(blank=True, choices=[('К', 'Капитан'), ('Б', 'Базовый состав'), ('Л', 'Легионер')], max_length=1, null=True, verbose_name='флаг')),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='баллы')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rating.Person', verbose_name='игрок')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocol.Claim', verbose_name='команда')),
            ],
            options={
                'verbose_name': 'посещение',
                'verbose_name_plural': 'посещения',
            },
        ),
    ]
