# Generated by Django 2.2.7 on 2019-12-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='attendance',
            name='patronymic',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
