# Generated by Django 2.2.7 on 2019-12-06 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_auto_20191204_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='protocol.Claim', verbose_name='команда'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='rating.Team', verbose_name='команда на сайте рейтинга'),
        ),
    ]
