# Generated by Django 2.2.7 on 2019-12-03 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '__first__'),
        ('accounting', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='наименование')),
                ('short_name', models.CharField(max_length=30, verbose_name='краткое наименование')),
                ('address', models.CharField(max_length=300, verbose_name='адрес')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота')),
            ],
            options={
                'verbose_name': 'место проведения',
                'verbose_name_plural': 'места проведения',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='дата и время')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='наименование')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('difficulty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('teams_main', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='команд всего')),
                ('teams_disc', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='команд со скидкой')),
                ('teams_free', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='команд, играющих бесплатно')),
                ('fee_main', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='взнос')),
                ('fee_main_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='взнос в рублях')),
                ('fee_disc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='взнос со скидкой')),
                ('fee_disc_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='взнос со скидкой в рублях')),
                ('fee_comment', models.TextField(blank=True, null=True, verbose_name='комментарий к скидке')),
                ('pay_before', models.DateField(blank=True, null=True, verbose_name='оплатить до')),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='сумма оплаты')),
                ('payment_rub', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='сумма оплаты в рублях')),
                ('payment_details', models.CharField(blank=True, max_length=120, verbose_name='реквизиты платежа')),
                ('payment_day', models.DateField(blank=True, null=True, verbose_name='дата оплаты')),
                ('notify_by', models.TextField(blank=True, verbose_name='уведомить об оплате')),
                ('fee_player', models.DecimalField(blank=True, decimal_places=2, default=300, max_digits=8, null=True, verbose_name='индивидуальный взнос')),
                ('fee_points', models.DecimalField(blank=True, decimal_places=2, default=3, max_digits=8, null=True, verbose_name='цена по абонементу')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Currency', verbose_name='валюта')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.Location', verbose_name='место')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.PaymentMethod', verbose_name='способ оплаты')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rating.Tournament', verbose_name='турнир чгк')),
            ],
            options={
                'verbose_name': 'игра ЧГК',
                'verbose_name_plural': 'игры ЧГК',
            },
        ),
    ]
