# Generated by Django 2.2.7 on 2019-12-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_remove_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка'),
        ),
    ]
